	(******************************)
	(*                            *)
	(*     EXPORTED VARIABLES     *)
	(*                            *)
	(******************************)

	VAR_GLOBAL
	p_MotorSpeedTarget AT %MW1.0 : REAL; 
	{G:"MONITOR"}
	v_Position AT %MD2.0 : REAL; 
	v_Speed AT %MD2.4 : REAL; 
	v_Torque AT %MD2.8 : REAL; 
	v_LoadPosition AT %MD2.12 : REAL; 
	v_LoadSpeed AT %MD2.16 : REAL; 
	v_rms_Iq AT %MD2.20 : REAL; 
	v_rms_Id AT %MD2.24 : REAL; 
	END_VAR

