	(******************************)
	(*                            *)
	(*     EXPORTED VARIABLES     *)
	(*                            *)
	(******************************)

	VAR_GLOBAL
	p_MotorSpeedTarget AT %MW1.0 : REAL; 
	p_ControlMode AT %MW1.8 : INT; 
	p_MotorTorqueRef AT %MD1.12 : REAL; 
	v_Speed AT %MD2.4 : REAL; 
	v_Torque AT %MD2.8 : REAL; 
	v_LoadPosition AT %MD2.12 : REAL; 
	v_LoadSpeed AT %MD2.16 : REAL; 
	v_rms_Iq AT %MD2.20 : REAL; 
	v_rms_Id AT %MD2.24 : REAL; 
	v_rms_Iout AT %MD2.28 : REAL; 
	v_rms_Vdc AT %MD2.32 : REAL; 
	v_rms_Vo AT %MD2.36 : REAL; 
	v_rms_Speed AT %MD2.40 : REAL; 
	v_temperature AT %MD2.44 : REAL; 
	v_mean_Iq AT %MD2.48 : REAL; 
	v_mean_Id AT %MD2.52 : REAL; 
	v_mean_Iout AT %MD2.56 : REAL; 
	v_mean_Vdc AT %MD2.60 : REAL; 
	v_mean_Vo AT %MD2.64 : REAL; 
	v_mean_Speed AT %MD2.68 : REAL; 
	{G:"MONITOR"}
	v_Position AT %MD2.0 : REAL; 
	END_VAR

